### ISSUE TITLE
OTB versions

### ISSUE THREAD

**Issue by Jajafarov** [turquoise-hexagon/cherry#12]
Now that pango has stopped supporting bdf fonts, would it be possible to have them in otb formats as well? Users get discouraged from using cherry when they know that they can't use it in programs like rofi and dunst.

**Comment by Jajafarov** [comment]
Just tried the otb version in rofi and many of the letters come out different. I only bothered to check upper and lower case English letters. 
Uppercase: A J M N Q U W
Lowercase: a b d e h j l m n p q u w

Not sure if anything can be done since it's converted with fonttosfnt so it probably depends on how well that works.

**Comment by turquoise-hexagon** [comment]
would it be possible to provide a screenshot along with the installed pango version ? it's a bit hard to tell what's wrong exactly with that little information

**Comment by Jajafarov** [comment]
Pango version: 1:1.44.6-1
Images (White is OTB):
![1568387319-area-screenshot](https://user-images.githubusercontent.com/9387120/64873553-9eff5100-d649-11e9-9d04-83af080e107d.png)
![1568387345-area-screenshot](https://user-images.githubusercontent.com/9387120/64873554-9eff5100-d649-11e9-899e-219efbf53df8.png)
![1568387447-area-screenshot](https://user-images.githubusercontent.com/9387120/64873555-9eff5100-d649-11e9-8d1c-526f2419e30e.png)
![1568387488-area-screenshot](https://user-images.githubusercontent.com/9387120/64873557-9eff5100-d649-11e9-8ced-5d819c1158d3.png)

**Comment by Jajafarov** [comment]
Looking at the images in repo again, it seems like my bitmap fonts were rendered incorrectly from the beginning and I got used to it. So this otb version is rendered correctly.
