### ISSUE TITLE
Lowercase "a"

### ISSUE THREAD

**Issue by harg** [turquoise-hexagon/cherry#5]
Thank you for your work on this font! ❤️ 

Is it possible to make a variant with an alternative lowercase "a" like this : 

![image](https://user-images.githubusercontent.com/34398/43661127-5ee067d0-9761-11e8-95e8-5dd626571418.png)

I find the current version hard to read (too similar to the lowercase "o".

**Comment by turquoise-hexagon** [comment]
I reverted the lowercase "a" to make it more consistent with the other sizes but I totally understand your request, I was recently looking for a solution to make the font "user configurable" but wasn't able to come up with something decent so if you have some idea definitely hit me up.

For the issue itself, I'll considere reverting it as soon as I have access to a computer again.

Cheers !

**Comment by harg** [comment]
I know that the Iosevka font author has written some scripts to customize the font : https://github.com/be5invis/Iosevka#build-your-own-style

Maybe you can check that out.

**Comment by turquoise-hexagon** [comment]
Fixed in the latest commit.

Also since cherry is a bitmap font I don't think I can use the same tools as Iosevka, but thanks for the suggestion !
