### ISSUE TITLE
Are there any plans for a 12 px variant?

### ISSUE THREAD

**Issue by rightbrace** [turquoise-hexagon/cherry#6]
This is a truly excellent font, however I find that on my display (1366x768, 11in) 11 is too small to be comfortably read, and 13 is far too big (and it isn’t quite as nice as 11).

I don’t know if others have this issue, but it would be nice to know if you’re going to continue on this font. (Seriously though, congratulations, this is a great font)

Postscript - I am unable to edit the title - having typed this on mobile I did not notice the typo

**Comment by turquoise-hexagon** [comment]
it wasn't planned but I'll see if i can come up with something in between 11 and 13px.

**Comment by turquoise-hexagon** [comment]
![12](https://user-images.githubusercontent.com/15786638/45100777-5c4b9480-b12a-11e8-8d1a-4832bb415ad0.png)

I made a basic charset for testing purposes, looks good to you ?

**Comment by turquoise-hexagon** [comment]
@rightbrace done !

**Comment by rightbrace** [comment]
@turquoise-hexagon This looks great, I'm amazed at how quickly you added it. Much more readable on a higher dpi, without getting too big.
